### ISSUE TITLE
Other sysfs peripherals

### ISSUE THREAD

**Issue by andreacioni** [brian-armstrong/gpio#5]
Hi Brian
Thanks for your work! I appreciate very much this project.
I'm preparing to test your library on Beaglebone Black and UDOO. Hope this help 😊

Just a question, did you plan to add also some other peripherals (PWM for example)? I can try to do that, but I'm not sure you want such things in your project (name of your repo is _gpio_). Let me know

Cheers,
Andrea Cioni

**Comment by brian-armstrong** [comment]
I don't necessarily have plans to add that, but I think it makes sense to put in this project. Anything that's in the domain of gpio-type things and uses sysfs seems like a good addition

Thanks
Brian
